package ma.formations.jdbc.presentation.controller;

import java.io.IOException;
import jakarta.servlet.ServletException;
import jakarta.servlet.annotation.WebServlet;
import jakarta.servlet.http.HttpServlet;
import jakarta.servlet.http.HttpServletRequest;
import jakarta.servlet.http.HttpServletResponse;
import ma.formations.jdbc.service.IService;
import ma.formations.jdbc.service.ServiceImpl;
import ma.formations.jdbc.service.model.Article;

@WebServlet("/createArticle.do")
public class CreateArticleServlet extends HttpServlet {
    private static final long serialVersionUID = 1L;
    private IService service = new ServiceImpl();

    protected void doGet(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {
        request.getRequestDispatcher("/view/article-form.jsp").forward(request, response);
    }

    protected void doPost(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {
        try {























            // Remove the id from the parameters since it will be auto-generated
            String description = request.getParameter("description");
            Double quantite = Double.parseDouble(request.getParameter("quantite"));
            Double price = Double.parseDouble(request.getParameter("price"));

            // Create the Article object with a null id (auto-generated by the database)
            Article article = new Article(null, description, quantite, price);

            // Save the article
            service.saveArticle(article);

            // Redirect to the articles listing page after successful creation
            response.sendRedirect(request.getContextPath() + "/articles.do");
        } catch (NumberFormatException e) {
            request.setAttribute("error", "Invalid input format");
            request.getRequestDispatcher("/view/article-form.jsp").forward(request, response);
        }
    }
}
